config/routes.rb
SolarCanvasser::Application.routes.draw do

  resources :referrers do 
    collection do 
      resources :leads
      resources :opportunities
    end
  end

  root :to => 'main#dashboard'

end

app/models/lead.rb
class Lead < ActiveRecord::Base
  attr_accessible :address, :name
  belongs_to :referrer
end

app/models/opportunity.rb
class Opportunity < ActiveRecord::Base
  attr_accessible :address, :distance, :name
  belongs_to :referrer
end

app/models/referrer.rb
class Referrer < ActiveRecord::Base
  attr_accessible :name
  has_many :leads
  has_many :opportunities
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController

  def index
    @leads = Lead.all
  end

  def show
    @lead = Lead.find(params[:id])
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def dashboard
    
  end
  
end

app/controllers/opportunities_controller.rb
class OpportunitiesController < ApplicationController
  def index
    @opportunities = Opportunity.all
  end

  def show
    @opportunity = Opportunity.find(params[:id])
  end
end

app/controllers/referrers_controller.rb
class ReferrersController < ApplicationController
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/opportunities_helper.rb
module OpportunitiesHelper
end

app/helpers/referrers_helper.rb
module ReferrersHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Myapp" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= link_to image_tag("logo.png"), root_path %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/leads/index.html.erb
<h1>My Leads</h1>
<ul>
  <% @leads.each do |lead| %>
    <li><%= link_to lead.name, lead_path(lead) %></li>
  <% end %>
</ul>

<%= link_to "Dashboard", root_path, class: "btn btn-large btn-default" %>

app/views/leads/show.html.erb
<h1><%= @lead.name %></h1>

<%= link_to "Back", :back, class: "btn btn-large btn-default" %>

app/views/main/dashboard.html.erb
<h1>Dashboard</h1>

<%= link_to "Oppportunities", opportunities_path, class: "btn btn-default" %>
<%= link_to "View Leads", leads_path, class: "btn btn-default" %>
<%= link_to "Start Estimate", "http://app.solarlist.com/get-an-estimate", class: "btn btn-default" %>

app/views/opportunities/index.html.erb
<h1>Opportunities</h1>
<ul>
  <% @opportunities.each do |o| %>
    <li><%= link_to o.name, opportunity_path(o) %></li>
  <% end %>
</ul>

<%= link_to "Dashboard", root_path, class: "btn btn-large btn-default" %>

app/views/opportunities/show.html.erb
<%= @opportunity.name %>

<%= link_to 'Back', :back, class: "btn btn-large btn-default" %>